=== Record

A record is the smallest unit you can load from and store in the database.
Records come in three types:

- Document
- Vertex
- Edge

[discrete]
==== Document

Documents are softly typed and are defined by schema types, but you can also use them in a schema-less mode too.
Documents handle fields in a flexible manner.
You can easily import and export them in JSON format.
For example,

[source,json]
----
{
  "name":"Jay",
  "surname":"Miner",
  "job":"Developer",
  "creations":[{
    "name":"Amiga 1000",
    "company":"Commodore Inc."
  },{
    "name":"Amiga 500",
    "company":"Commodore Inc."
  }]
}
----

[discrete]
==== Vertex

In Graph databases the vertices (also named vertexes), or nodes represent the main entity that holds the information.
It can be a Patient, a Company or a Product.
Vertices are themselves documents with some additional features.
This means they can contain embedded records and arbitrary properties exactly like documents.
Vertices are connected with other vertices through Edges.

[discrete]
==== Edge

An Edge, or Arc, is the connection between two vertices.
Edges can be unidirectional and bidirectional.
One edge can only connect two vertices.

For more information on connecting vertices in general, see <<Relationships,Relationships>> below.

[[RID]]
[discrete]
==== Record ID

When ArcadeDB generates a record, it auto-assigns a unique identifier called a Record ID, RID for short.
The syntax for the RID is the pound sign with the bucket identifier, colon, and the position like so:

`#<bucket-identifier>:<record-position>`.

- **bucket-identifier**: This number indicates the bucket id to which the record belongs.
Positive numbers in the bucket identifier indicate persistent records.
You can have up to 2,147,483,648 buckets in a database.

- **record-position**: This number defines the absolute position of the record in the bucket.

`#-1:-1` is a null RID.

NOTE: The prefix character `#` is mandatory.

Each Record ID is immutable, universal, and is never reused.
Additionally, records can be accessed directly through their RIDs at{nbsp}O(1){nbsp}complexity which means the query speed is constant, unaffected by database size.
For this reason, you don't need to create a field to serve as the primary key as you do in Relational databases.

[[Types]]
=== Types

The concept of the Type is taken from the http://en.wikipedia.org/wiki/Object-oriented_programming[Object Oriented Programming] paradigm, sometimes as 'Class'.
In ArcadeDB, types define records.
It is closest to the concept of a 'Table' in Relational databases and a 'Class' in an Object Database.

Types can be schema-less, schema-full, or a mix.
They can inherit from other types, creating a tree of types. http://en.wikipedia.org/wiki/Inheritance_%28object-oriented_programming%29[Inheritance], in this context, means that a subtype extends a parent type, inheriting all of its attributes.
Practically, this is done by <<SQL-Create-Type,extending a type>> or <<SQL-Alter-Type,setting a super-type>>. 

Each type has its own <<Buckets,buckets (data files)>>.
A type can support multiple buckets.
When you execute a query against a type, it automatically fetches from all the buckets that are part of the type.
When you create a new record, ArcadeDB selects the bucket to store it in using a <<Bucket-Selection,configurable strategy>>.

As a default, ArcadeDB creates as many buckets per type as many cores (processors) the host machine has.
In this, CRUD operations can go full speed in parallel with zero contention between CPUs and/or COREs.
Having many buckets per type means having more files at file system level.
Check if your Operative System has any limitation with the number of files supported and opened at the same time (`ulimit` for Unix-like systems).

NOTE: You can query the defined types by executing the following SQL query: `select from schema:types`.

[[Buckets]]
=== Buckets

Where types provide you with a logical framework for organizing data, buckets provide physical or in-memory space in which ArcadeDB actually stores the data.
Each bucket is one file at file system level.
It is comparable to the "collection" in Document databases, the "table" in Relational databases and the "cluster" in OrientDB.
You can have up to 2,147,483,648 buckets in a database.

A bucket can only be part of one type. This means two types can not share the same bucket.

When you create a new type, the <<SQL-Create-Type,`CREATE TYPE`>> statement automatically creates the physical buckets (files) that serve as the default location in which to store data for that type.
ArcadeDB forms the bucket names by using the type name + underscore + a sequential number starting from 0. For example, the first bucket for the type `Beer` will be `Beer_0` and the correspondent file in the file system will be `Beer_0.31.65536.bucket`.
ArcadeDB creates additional buckets for each type, (one for each CPU core on the server), to improve performance of parallelism.

[discrete]
==== Types vs. Buckets in Queries

The combination of types and buckets is very powerful and has a number of use cases.
In most case, you can work with Types and you will be fine.
But if you are able to split your database into multiple buckets, you could address a specific bucket based instead of the entire Type.
By wisely using the buckets to divide your database in a way that help you with the retrieval means zero or less use of indexes.
Indexes slow down insertion and take space on disk and RAM.
In most cases you need indexes to speed up your queries, but in some use cases you could totally or partially avoid using indexes and still having good performance on queries.

[discrete]
==== One bucket per period

Consider an example where you create a type `Invoice`, with one bucket per year. `Invoice_2015` and `Invoice_2016`.
You can query all invoices using the type as a target with the <<SQL-Select,`SELECT`>> statement.

[source,sql]
----
arcadeDB> SELECT FROM Invoice
----

In addition to this, you can filter the result set by the year.
The type `Invoice` includes a `year` field, you can filter it through the <<Filtering,`WHERE`>> clause.

[source,sql]
----
arcadeDB> SELECT FROM Invoice WHERE year = 2016
----

You can also query specific records from a single bucket.
By splitting the type `Invoice` across multiple buckets, (that is, one per year in our example), you can optimize the query by narrowing the potential result set.

```sql
arcadeDB> SELECT FROM BUCKET:Invoice_2016
```

By using the explicit bucket instead of the logical type, this query runs significantly faster, because ArcadeDB can narrow the search to the targeted bucket.
No index is needed on the year, because all the invoices for year 2016 will be stored in the bucket `Invoice_2016` by the application.

[discrete]
==== One bucket per location

Like with the example above, we could split our records by location creating one bucket per location.
Example:

[source,sql]
----
CREATE BUCKET Customer_Europe
CREATE BUCKET Customer_Americas
CREATE BUCKET Customer_Asia
CREATE BUCKET Customer_Other

CREATE VERTEX TYPE Customer BUCKET Customer_Europe,Customer_Americas,Customer_Asia,Customer_Other
----

Here we are using the graph model by creating a vertex type, but it's the same with documents.
Use <<SQL-Create-Type,`CREATE DOCUMENT TYPE`>> instead.

Now in your application store the vertices or documents in the right bucket, based on the location of such customer.
You can use any API and set the bucket.
If you're using SQL, this is the way you can insert a new Customer into a specific bucket.

[source,sql]
----
arcadeDB> INSERT INTO BUCKET:Customer_Europe CONTENT { firstName: 'Enzo', lastName: 'Ferrari' }
----

Since a bucket can only be part of one type, when you use the bucket notation with SQL, the type is inferred from the bucket, "Customer" in this case.

When you're looking for customers based in Europe, you could execute this query:

[source,sql]
----
arcadeDB> SELECT FROM BUCKET:Customer_Europe
----

You can go even more specific by creating a bucket per country, not just for continent, and query from that bucket.
Example:

[source,sql]
----
CREATE BUCKET 'Customer_Europe_Italy'
CREATE BUCKET 'Customer_Europe_Spain'
----

Now get all the customers that live in Italy.

[source,sql]
----
arcadeDB> SELECT FROM BUCKET:Customer_Europe_Italy
----

You can also specify a list of buckets in your query.
This is the query to retrieve both Italian and Spanish customers.

[source,sql]
----
arcadeDB> SELECT FROM BUCKET:[Customer_Europe_Italy,Customer_Europe_Spain]
----

[[Relationships]]
=== Relationships

ArcadeDB supports two kinds of relationships: **referenced** and **embedded**.
It can manage relationships in a schema-full or schema-less scenario.

[discrete]
==== Referenced Relationships

In Relational databases, tables are linked through `JOIN` commands, which can prove costly on computing resources.
ArcadeDB manages relationships natively without computing `JOIN`'s by storing direct links to the target objects of the relationship. This boosts the load speed for the entire graph of connected objects, such as in Graph and Object database systems.

Example

```
    Record A -------------> Record B
 TYPE=Customer            TYPE=Invoice
    RID #5:23               RID #10:2
```

[discrete]
==== Embedded Relationships

When using Embedded relationships, ArcadeDB stores the relationship within the record that embeds it.
These relationships are stronger than Reference relationships.
You can represent it as a http://en.wikipedia.org/wiki/Class_diagram#Composition[UML Composition relationship].

Embedded records do not have their own <<RID,RID>>, given that you can't directly reference it through other records.
It is only accessible through the container record.

In the event that you delete the container record, the embedded record is also deleted.
For example,

```
    Record A <>----------> Record B
   TYPE=Account          TYPE=Address
    RID #5:23               NO RID
```

Here,record `A` contains the entirety of record `B` in the property `address`.
You can reach record `B` only by traversing the container record.
For example,

```
arcadeDB> SELECT FROM Account WHERE address.city = 'Rome'
```

[discrete]
==== 1:1 and n:1 Embedded Relationships

ArcadeDB expresses relationships of these kinds using the `EMBEDDED` type.

[discrete]
==== 1:n and n:n Embedded Relationships

ArcadeDB expresses relationships of these kinds using a list or a map of links, such as:

- `LIST` An ordered list of records.
- `MAP` An ordered map of records as the value and a string as the key, it doesn't accept duplicate keys.

[discrete]
==== Inverse Relationships

In ArcadeDB, all Edges in the Graph model are bidirectional.
This differs from the Document model, where relationships are always unidirectional, requiring the developer to maintain data integrity.
In addition, ArcadeDB automatically maintains the consistency of all bidirectional relationships.

=== Database

Each server or Java VM can handle multiple database instances, but the database name must be unique.

[[Database-URL]]
[discrete]
==== Database URL

ArcadeDB uses its own http://en.wikipedia.org/wiki/Uniform_Resource_Locator[URL] format, of engine and database name as `<engine>:<db-name>`.
The embedded engine is the default and can be omitted.
To open a database on the local file system you can use directly the path as URL.

[discrete]
==== Database Usage

You must always close the database once you finish working on it.

NOTE: ArcadeDB automatically closes all opened databases, when the process dies gracefully (not by killing it by force).
This is assured if the Operating System allows a graceful shutdown.
For example, on Unix/Linux systems using `SIGTERM`, or in Docker `exit code 143` instead of `SIGKILL`, or in Docker `exit code 137`.)
