
[[inheritance]]
=== Inheritance

Unlike many object-relational mapping tools, ArcadeDB does not split documents between different types.
Each document resides in one or a number of buckets associated with its specific type.
When you execute a query against a type that has subtypes, ArcadeDB searches the buckets of the target type and all subtypes.

[discrete]
#### Declaring Inheritance in Schema

In developing your application, bear in mind that ArcadeDB needs to know the type inheritance relationship.

For example,

[source,java]
----
DocumentType account = database.getSchema().createDocumentType("Account");
DocumentType company = database.getSchema().createDocumentType("Company").addSuperType(account);
----

[discrete]
#### Using Polymorphic Queries

By default, ArcadeDB treats all queries as polymorphic.
Using the example above, you can run the following query from the console:

[source,sql]
----
SELECT FROM Account WHERE name.toUpperCase() = 'GOOGLE'
----

This query returns all instances of the types `Account` and `Company` that have a property name that matches `Google`.

[discrete]
#### How Inheritance Works

Consider an example, where you have three types, listed here with the bucket identifier in the parentheses.

++++
<svg class="dgm-svg" viewBox="0 0 1200 200"
     xmlns="http://www.w3.org/2000/svg"
     role="img" aria-label="Type inheritance: ArcadeData (bucket 27) extends Company (bucket 13) which extends Account (bucket 10).">
  <defs>
    <marker id="dgm-arrow-inheritance" markerWidth="10" markerHeight="10" refX="9" refY="5" orient="auto" markerUnits="strokeWidth">
      <path d="M0,0 L10,5 L0,10 z" class="dgm-arrowhead"/>
    </marker>
  </defs>
  <g class="dgm-box dgm-box-blue">
    <rect x="80"  y="60" width="260" height="80" rx="8"/>
    <text x="210" y="108" text-anchor="middle" class="dgm-title">ArcadeData(27)</text>
  </g>
  <g class="dgm-box dgm-box-purple">
    <rect x="470" y="60" width="260" height="80" rx="8"/>
    <text x="600" y="108" text-anchor="middle" class="dgm-title">Company(13)</text>
  </g>
  <g class="dgm-box dgm-box-green">
    <rect x="860" y="60" width="260" height="80" rx="8"/>
    <text x="990" y="108" text-anchor="middle" class="dgm-title">Account(10)</text>
  </g>
  <line x1="340" y1="100" x2="465" y2="100" class="dgm-conn" marker-end="url(#dgm-arrow-inheritance)"/>
  <line x1="730" y1="100" x2="855" y2="100" class="dgm-conn" marker-end="url(#dgm-arrow-inheritance)"/>
</svg>
++++

By default, ArcadeDB creates a separate bucket for each type.
It indicates this bucket by the `defaultBucketId` property in a type and indicates the bucket used by default when not specified.
However, a type has a property `bucketIds`, (as `int[]`), that contains all the buckets able to contain the records of that type. The properties `bucketIds` and `defaultBucketId` are the same by default.

When you execute a query against a type, ArcadeDB limits the result-sets to only the records of the buckets contained in the `bucketIds` property.
For example,

[source,sql]
----
SELECT FROM Account WHERE name.toUpperCase() = 'GOOGLE'
----

This query returns all the records with the name property set to `GOOGLE` from all three types, given that the base type `Account` was specified.
For the type `Account`, ArcadeDB searches inside the buckets `10`, `13` and `27`, following the inheritance specified in the schema.
