[[api-reference]]
[[reference]]
= Reference

ArcadeDB provides xref:reference/http-api/http.adoc#http-json-api[HTTP/JSON API] to interface to the server from a remote application.
You can use any programming language that supports HTTP calls (pretty much any language) or use a driver to have a little abstraction over xref:reference/http-api/http.adoc#http-json-api[HTTP/JSON API].

[%header,cols="20%,60%,20%"]
|===
| Language | Project URL | License
| Java | Bundled with the project. Look at `Remote Database` class | Apache 2
| CHICKEN Scheme | http://wiki.call-cc.org/eggref/5/arcadedb | zlib-acknowledgement
| Elixir | https://github.com/mindreframer/arcadex | MIT
| .NET | https://github.com/tetious/ArcadeDb.Client | Apache 2
| PHP (Laravel) | https://github.com/skcheung/laravel-arcadedb | ?
| Python | https://github.com/adaros92/arcadedb-python-driver | Apache 2
| Python | https://github.com/ExtReMLapin/pyarcade | Apache 2
| Python | https://github.com/stevereiner/arcadedb-python | Apache 2
| Python (embedded) | https://github.com/humemai/arcadedb-embedded-python | Apache 2
| Ruby | https://github.com/topofocus/arcadedb | MIT
| RUST | https://crates.io/crates/arcadedb-rs | Apache 2
| Typescript | https://sprite.tragedy.dev/ | MIT
|===

[[query-languages]]
== Query Languages

* xref:reference/sql/chapter.adoc#sql[SQL] - The most widely recognized query language standard
* xref:reference/cypher/chapter.adoc#cypher[Open Cypher] - Declarative graph query language
* xref:reference/gremlin/gremlin.adoc#gremlin-api[Gremlin] - Apache TinkerPop graph traversal language
* xref:reference/graphql/graphql.adoc#graphql[GraphQL] - Query language for APIs
* xref:reference/mongodb-ql/mongo.adoc#mongodb-query-language[MongoDB Query Language] - MongoDB-compatible query language
* xref:reference/redis-ql/redis.adoc#redis-query-language[Redis] - Redis-compatible commands

:leveloffset: +1

:leveloffset: -1

== APIs

:leveloffset: +1

:leveloffset: -1

// >>> chapter-cards (auto-generated) <<<
++++
<div class="chapter-cards">
  <a class="chapter-card" href="reference/datatypes.html"><span class="chapter-card-title">Data Types</span></a>
  <a class="chapter-card" href="reference/binary-types.html"><span class="chapter-card-title">Binary Types (BLOB)</span></a>
  <a class="chapter-card" href="reference/managing-dates.html"><span class="chapter-card-title">Managing Dates</span></a>
  <a class="chapter-card" href="reference/sql/chapter.html"><span class="chapter-card-title">SQL</span></a>
  <a class="chapter-card" href="reference/cypher/chapter.html"><span class="chapter-card-title">Open Cypher</span></a>
  <a class="chapter-card" href="reference/gremlin/chapter.html"><span class="chapter-card-title">Chapter</span></a>
  <a class="chapter-card" href="reference/graphql/chapter.html"><span class="chapter-card-title">Chapter</span></a>
  <a class="chapter-card" href="reference/mongodb-ql/chapter.html"><span class="chapter-card-title">Chapter</span></a>
  <a class="chapter-card" href="reference/redis-ql/chapter.html"><span class="chapter-card-title">Chapter</span></a>
  <a class="chapter-card" href="reference/java-api/chapter.html"><span class="chapter-card-title">Chapter</span></a>
  <a class="chapter-card" href="reference/grpc-api/chapter.html"><span class="chapter-card-title">gRPC API</span></a>
  <a class="chapter-card" href="reference/mcp/chapter.html"><span class="chapter-card-title">Chapter</span></a>
  <a class="chapter-card" href="reference/graph-algorithms/chapter.html"><span class="chapter-card-title">Graph Algorithms</span></a>
  <a class="chapter-card" href="reference/vector-functions/chapter.html"><span class="chapter-card-title">Vector Functions</span></a>
  <a class="chapter-card" href="reference/time-series/chapter.html"><span class="chapter-card-title">Time Series Reference</span></a>
  <a class="chapter-card" href="reference/requirements.html"><span class="chapter-card-title">Requirements</span></a>
  <a class="chapter-card" href="reference/settings.html"><span class="chapter-card-title">Settings</span></a>
  <a class="chapter-card" href="reference/sql-syntax.html"><span class="chapter-card-title">SQL Syntax</span></a>
  <a class="chapter-card" href="reference/extended-functions.html"><span class="chapter-card-title">Extended Functions Reference</span></a>
</div>
++++
// <<< chapter-cards (auto-generated) >>>
