
=== Server

To start ArcadeDB as a server run the script `server.sh` under the `bin` directory of ArcadeDB distribution

```
~/arcadedb $ cd bin
~/arcadedb/bin $ ./server.sh

<ArcadeDB_0> Starting ArcadeDB Server... [ArcadeDBServer]
<ArcadeDB_0> - JMX Metrics Started... [ArcadeDBServer]
<ArcadeDB_0> - Starting HTTP Server (host=0.0.0.0 port=2480)... [HttpServer]
XNIO version 3.3.8.Final [xnio]
XNIO NIO Implementation Version 3.3.8.Final [nio]
<ArcadeDB_0> - HTTP Server started (host=0.0.0.0 port=2480) [HttpServer]
<ArcadeDB_0> ArcadeDB Server started (CPUs=8 MAXRAM=1.92GB) [ArcadeDBServer]
```

By default, the following components start with the server:
- JMX Metrics, to monitor server performance and statistics
- HTTP Server, that listens on port 2480 by default

In the output above, the name `ArcadeDB_0` is the server name. By default `ArcadeDB_0` is used.
To specify a different name define it with the setting <<#_settings,`server.name`>>, example:

```
./server.sh -Darcadedb.server.name=ArcadeDB_Europe_0
```

In HA configuration, it's mandatory all the servers in cluster have different names.

==== Create default database(s)

Instead of starting a server and then connect to it to create the default databases, ArcadeDB Server takes an initial default databases list by using
the setting <<#_settings,`server.defaultDatabases`>>.

```
./server.sh -Darcadedb.server.defaultDatabases=Universe[elon:musk]
```

With the example above the database "Universe" will be created if doesn't exist, with user "elon", password "musk".

Once the server is started, multiple clients can be connected to the server by using one of the supported protocols:

- <<#_http-json,HTTP/JSON>>
- Any <<#_mongodb-protocol-wrapper,MongoDB Driver>>
- Any <<#_redis-protocol-wrapper,Redis Driver>>

==== Plugins

===== MongoDB Protocol Wrapper

ArcadeDB Server supports a subset of the https://mongodb.com[MongoDB] protocol, like CRUD operations and queries.

To start the MongoDB plugin, enlist it in the <<#_settings,`server.plugins`>> settings. To specify multiple plugins, use the comma `,` as separator. Example:

```
./server.sh -Darcadedb.server.plugins=MongoDB:com.arcadedb.mongodbw.MongoDBWrapperPlugin
```

The Server output will contain this line:

```
2018-10-09 18:47:01:692 INFO  <ArcadeDB_0> - Plugin MongoDB started [ArcadeDBServer]
```

===== Redis Protocol Wrapper

ArcadeDB Server supports a subset of the https://redis.io[Redis] protocol, like CRUD operations and queries.

To start the Redis plugin, enlist it in the <<#_settings,`server.plugins`>> settings. To specify multiple plugins, use the comma `,` as separator. Example:

```
./server.sh -Darcadedb.server.plugins=Redis:com.arcadedb.redisw.RedisWrapperPlugin
```

The Server output will contain this line:

```
2018-10-09 18:47:58:395 INFO  <ArcadeDB_0> - Plugin Redis started [ArcadeDBServer]
```
