[[sql-alter-materialized-view]]
[discrete]
= SQL - `ALTER MATERIALIZED VIEW`

Changes the refresh mode of an existing materialized view.

NOTE: `ALTER MATERIALIZED VIEW` is planned for a future release and is not yet implemented.

*Syntax*

[source,sql]
----
ALTER MATERIALIZED VIEW <name>
  REFRESH MANUAL | REFRESH INCREMENTAL | REFRESH EVERY <n> SECOND | MINUTE | HOUR
----

* *`<name>`* The name of the materialized view to alter.
* *`REFRESH MANUAL`* Switches the view to manual refresh mode.
* *`REFRESH INCREMENTAL`* Switches the view to incremental refresh mode (automatic after each relevant commit).
* *`REFRESH EVERY <n> SECOND | MINUTE | HOUR`* Switches the view to periodic refresh mode at the specified interval.

For more information, see:

* xref:how-to/data-modeling/materialized-views.adoc#materialized-views[Materialized Views]
* xref:reference/sql/sql-create-materialized-view.adoc#sql-create-materialized-view[`CREATE MATERIALIZED VIEW`]
* xref:reference/sql/sql-refresh-materialized-view.adoc#sql-refresh-materialized-view[`REFRESH MATERIALIZED VIEW`]
