[[sql-create-property]]
[discrete]
= SQL - `CREATE PROPERTY`

Creates a new property in the schema.
It requires that the type for the property already exist on the database.

*Syntax*

----
CREATE PROPERTY
<type>.<property> [IF NOT EXISTS] <data-type> [OF <embd-type>]
[<property-constraint>[,]*]
----

* *`&lt;type&gt;`* Defines the type for the new property.
* *`&lt;property&gt;`* Defines the logical name for the property.
* *`&lt;data-type&gt;`* Defines the property data type. For supported types, see the table below.
* *`&lt;embd-type&gt;`* Defines the property's embedded type (only for embedding property types `EMBEDDED`, `LIST`, `MAP`, as well as `LINK`).
* *`&lt;property-constraint&gt;`* See xref:reference/sql/sql-alter-property.adoc#sql-alter-property[`ALTER PROPERTY`] `&lt;attribute-name&gt; * &lt;attribute-value&gt;`
** `mandatory &lt;true|false&gt;` If true, the property must be present.
Default is *false*
** `notnull &lt;true|false&gt;` If true, the property, must be present and cannot be null.
Default is *false*
** `readonly &lt;true|false&gt;` If true, the property cannot be changed after the creation of the record.
Default is *false*
** `hidden &lt;true|false&gt;` If true, the property is not added to the result set when using * in projections such as in  `SELECT * FROM`; it is included when `SELECT FROM` is used or if the hidden property is part of the projection list .
Default is *false*
** `external &lt;true|false&gt;` If true, the property's value is stored in a paired external bucket instead of inline in the primary record.
Useful for vector embeddings, large strings, embedded JSON or other heavy payloads that should not be loaded by traversal-only queries.
See xref:concepts/external-properties.adoc#external-properties[External Properties] for the full picture.
Default is *false*
** `compression &lt;none|fast|max|auto&gt;` Compression policy for an `EXTERNAL` property's stored value.
Ignored for non-`EXTERNAL` properties.
`none` (default) stores the value raw, `fast` uses LZ4 fast encoder, `max` uses LZ4 HC for smaller files at the cost of write CPU, `auto` tries `fast` and keeps it only when it saves more than 10% of bytes.
The legacy alias `lz4` is accepted and stored as `fast`.
** `min &lt;number|string&gt;` Defines the minimum value for this property.
For number types it is the minimum number as a value.
For strings it represents the minimum number of characters.
For dates is the minimum date (uses the database date format).
For collections (lists, sets, maps) this attribute determines the minimally required number of elements.
** `max &lt;number|string&gt;` Defines the maximum value for this property.
For number types it is the maximum number as a value.
For strings it represents the maximum number of characters.
For dates is the maximum date (uses the database date format).
For collections (lists, sets, maps) this attribute determines the maximally allowed number of elements.
** `regexp &lt;string&gt;` Defines the mask to validate the input as a Regular Expression
** `default <any>` Defines default value if not present. Default is `null`.
** `IF NOT EXISTS` If specified, create the property only if not exists.
If a property with the same name already exists in the type, then no error is returned

IMPORTANT: The `hidden` attribute is currently deactivated and has no function!

NOTE: When you create a property, ArcadeDB checks the data for property and type.
In the event that persistent data contains incompatible values for the specified type, the property creation fails.
It applies no other constraints on the persistent data.

NOTE: When constraints are set, such as `mandatory`, `read-only`, etc., it's not possible to use the Gremlin syntax to add vertices and edges without incurring in a Validation exception.
The issue is that Gremlin API sets the properties after the creation of the vertex and edge.

NOTE: Properties of the type `LINK` may have the value `NULL`, furthermore accessing a
`LINK` property which is not set results also in a `NULL` value.

TIP: A mandatory property generally cannot have a default value `NULL` (the default default value).
     However, to force a default value `NULL` one can use `ifnull(NULL, NULL)` as explicit default value expression.

*Examples*

* Create the property `name` of the string type in the type `User`:

----
ArcadeDB> CREATE PROPERTY User.name STRING
----

* Create a property called `tags` in the type `Profile` only allowing list members of type string:

----
ArcadeDB> CREATE PROPERTY Profile.tags LIST OF STRING
----

* Create the property `friends`, as an embedded map:

----
ArcadeDB> CREATE PROPERTY Profile.friends MAP
----

* Create the property `address`, as an embedded document:

----
ArcadeDB> CREATE PROPERTY Profile.address EMBEDDED
----

* Create the property `createdOn` of type date with additional constraints:

----
ArcadeDB> CREATE PROPERTY Transaction.createdOn DATE (mandatory true, notnull true, readonly true, min "2010-01-01")
----

* Create the property `secret` of type string with hidden constraint:

----
ArcadeDB> CREATE PROPERTY Employee.secret STRING (hidden true, notnull true)
----

* Create the property `salary` only if it does not exist:

----
ArcadeDB> CREATE PROPERTY Employee.salary IF NOT EXISTS double
----

* Create the property `hiredAt` with the time of creation being the default value:

----
ArcadeDB> CREATE PROPERTY Employee.hiredAt DATETIME (readonly, default sysdate('YYYY-MM-DD HH:MM:SS'))
----

For more information, see:

* xref:reference/sql/sql-alter-property.adoc#sql-alter-property[`ALTER PROPERTY`]
* xref:reference/sql/sql-drop-property.adoc#sql-drop-property[`DROP PROPERTY`]

[[supported-types]]
*Supported Types*

ArcadeDB supports the following data types for standard properties:

[cols=5]
|===
| `BOOLEAN` | `BYTE` | `SHORT` | `INTEGER` | `LONG`
| `STRING` | `LINK` | `BINARY` | `DATE` | `DATETIME`
| `FLOAT` | `DOUBLE` | `DECIMAL` | |
|===

It supports the following data types for container properties:

[cols=3]
|===
| `LIST` | `MAP` | `EMBEDDED`
|===
