
=== OrientDB

- ArcadeDB "types" are the "classes" in OrientDB
- ArcadeDB "buckets" are similar to the "clusters" in OrientDB
- ArcadeDB shares the same database instance across threads. Much easier developing with ArcadeDB than with OrientDB with multi-threads applications
- ArcadeDB uses thread locals only to manage transactions, while OrientDB makes a strong usage of TL internally, making hard to pass the db instance across threads and a pool is needed
- There is no base V and E classes in ArcadeDB, but vertex and edge are first type citizens types of records
- ArcadeDB saves every type and property name in the dictionary to compress the record by storing only the names ids (varint)
- ArcadeDB keeps the MVCC counter on the page rather than on the record
- ArcadeDB manages everything as files and pages
- ArcadeDB allows custom page size per bucket/index
- ArcadeDB doesn't break record across pages, but rather create a placeholder pointing to the page that has the record. This allows the RID to be immutable without the complexity of managing split records
- ArcadeDB has light-weight edges, but they must be used with a different syntax. This avoid automatic upgrade of edges and unexpected bahavior
- ArcadeDB has a Leader/Replica replication model, no sharding. Instead OrientDB has a Multi-Master + sharding. For this reason, the ArcadeDB complexity is 100X less than OrientDB with some limitations that in practice are even less
- ArcadeDB replicates the pages across servers, so all the databases are identical at binary level

==== What ArcadeDB does not support

- ArcadeDB doesn't support storing records with a size major than the page size. You can always create a bucket with a larger page size, but this can be done only at creation time
- ArcadeDB remote server supports only HTTP/JSON, no binary protocol is available
- ArcadeDB doesn't provide a dirty manager, so it's up to the developer to mark the object to save by calling `.save()` method. This makes the code of ArcadeDB smaller without handling edge cases

==== What ArcadeDB has more than OrientDB

- ArcadeDB saves every type and property name in the dictionary to compress the record by storing only the names ids
- ArcadeDB asynchronous API automatically balance the load on the available cores
- ArcadeDB is much Faster, on single server it's easy to see 10X-20X improvement in performance, with 3 nodes it's about 50X-200X. With 10 servers it's >500X!
- ArcadeDB uses much less RAM. With the right tuning with settings, it's able to work with only 4MB of JVM heap
- ArcadeDB allows to execute operation in asynchronously way (by using `.async()`)
- ArcadeDB is lightweight, the engine is <200Kb
