[[Security]]
ArcadeDB manages the security at server level only.
This means if you work in embedded mode, there is no security available.
Any user can read and write in the database.
If you still want to use ArcadeDB in embedded mode, please start the server as embedded and get the database instances from the `ArcadeDBServer` instance.

The security configuration is stored in the `config/security.json` file.

** The security.json file is changing to support new features. Please follow https://github.com/ArcadeData/arcadedb/discussions/56[this discussion] until it's final and this documentation paragraph updated.**

[[Secuity-Policy]]
=== Security Policy

The default rule of security are pretty basic.
The username must be between 4 and 256 characters.
The password length must be between 8 and 256 characters.
You can implement your own security policy by providing your own implementation:

```
server.getSecurity().setCredentialsValidator( new DefaultCredentialsValidator(){
  @Override
  public void validateCredentials(final String userName, final String userPassword) throws ServerSecurityException {
    if( userPassword.equals("12345678")
      throw new ServerSecurityException("Guess who was not attending security lesson!");
  }
});
```

