[[Gremlin-API]]
===== Gremlin API

ArcadeDB supports Gremlin v3.4.x as query engine and in the Gremlin Server.
You can execute a gremlin query from pretty much everywhere.

====== Gremlin from Java API

In order to execute a Gremlin query, you need to include the relevant jars in your class path.
To execute a Gremlin query, use "gremlin" as first parameter in the query method.
Example:

```java
ResultSet result = database.query("gremlin", "g.V().has('name','Steve').has('lastName','Jobs').out('IsFriendOf')");
```

====== Gremlin through Postgres Driver

You can execute a Gremlin query against ArcadeDB server by using the <<Postgres-Driver,Postgres driver>> and prefixing the query with `{gremlin}`.
Example:

```Gremlin
"{gremlin} g.V().has('name','Steve').has('lastName','Jobs').out('IsFriendOf')"
```

ArcadeDB server will execute the query `g.V().has('name','Steve').has('lastName','Jobs').out('IsFriendOf')` using the Gremlin query language.

====== Gremlin through HTTP/JSON

You can execute a Gremlin query against ArcadeDB server by using <<HTTP-API,HTTP/JSON>> API.
Example of executing an idempotent query with HTTP GET command:

```Bash
curl "http://localhost:2480/query/graph/gremlin/g.V().has('name','Steve').has('lastName','Jobs').out('IsFriendOf')"
```

Example of executing a non-idempotent query (updates the database):

```Bash
curl -X POST "http://localhost:2480/command/graph" -d "{'language': 'gremlin', 'command': 'g.V().has(\"name\",\"Steve\").has(\"lastName\",\"Jobs\").out(\"IsFriendOf\")'}"
```

