[[HTTP-API-NODEJS]]
=== HTTP/JSON (JavaScript)

[discrete]
==== Sample Code

In NodeJS Javascript, HTTP/JSON requests can be made by installing the https://www.npmjs.com/package/axios[Axios HTTP package]. 

1. Ensure NodeJS and Node Package Manager are installed and accessible from the command prompt. If installed, `node -v` and `npm -v` will report their version numbers for confirmation.
2. Create a folder to contain a NodeJS project and a file in this folder called `test.js`. 
3. From this folder, run `npm install axios` to add the https://www.npmjs.com/package/axios[Axios HTTP package] to the folder/project.
4. Open `test.js` and add the needed code to be run.
5. Run the script from the command line with `node test.js`.

The following demonstrates a simple function which can be added to the javascript file. It will return records of the type `Profile` from a database named `mydb` and debug them to the command line.

[source,shell]
----
const axios = require('axios') 

// Make request 
const userPass = 'root:arcadedb-password';
const authString = 'Basic ' + btoa(userPass);
axios.post('http://serveraddress:2480/api/v1/command/mydb', //customize with your server address (or local host) and db name
    { "language": "sql", "command": "SELECT from Profile" }, //customize with your required command
    { headers : { 'Authorization' : authString, 'Content-Type': 'application/json' }}
  )

// Show response data 
.then(res => console.log(res.data)) 
.catch(err => console.log(err))
----
