==== `DatabaseAsyncExecutor` Interface

This is the class to manage asynchronous operations. To obtain an instance of DatabaseAsyncExecutor, use the method `.async()` in `<<#_-code-database-code-interface,Database>>`.

The Asynchronous API schedule the operation to be executed as soon as possible, but by a different thread. ArcadeDB optimizes the usage of asynchronous threads to be equals to the number of cores found in the machine (but it is still configurable). Use Asynchronous API if the response of the operation can be managed in asynchronous way and if you want to avoid developing Multi-Threads application by yourself.

===== Methods

[cols=5]
|===
|<<_query-language-command-callback-positionalparameters,query() positional parameters>>
|<<_query-language-command-callback-parametermap,query() parameter map>>
|<<_command-language-command-callback-positionalparameters,command() positional parameters>>
|<<_command-language-command-callback-parametermap,command() parameter map>>
|
|===

====== query( language, command, callback, positionalParameters )

Executes a query in asynchronous way, with optional positional parameters. This method returns immediately. This method only executes idempotent statements, namely `SELECT` and `MATCH`, that cannot change the database. The execution of any other commands will throw a `IllegalArgumentException` exception.

Syntax:

```java
Resultset query( String language, String command, AsyncResultsetCallback callback, Object... positionalParameters )
```

Where:

- `language`             is the language to use. Only "SQL" language is supported for now, but in the future multiple languages could be used
- `command`              is the command to execute. If the language supports prepared statements (SQL does), you can specify parameters by using `?` for positional replacement
- `callback`             is the callback to execute either if the query succeed (method `onOk()` is called, or in case of error, where the method `onError()` is called
- `positionalParameters` optional variable array of parameters to execute with the query

It returns a `Resultset` object where the result can be iterated.

Examples:

Simple query:

```java
db.async().query("sql", "select from V", new SQLCallback() {
  @Override
  public void onOk(ResultSet resultset) {
    while (resultset.hasNext()) {
      Result record = resultset.next();
      System.out.println( "Found record, name = " + record.getProperty("name"));
    }
  }

  @Override
  public void onError(Exception exception) {
    System.err.println("Error on executing query: " + exception );
  }
});
```

Query passing positional parameters:

```java
ResultSet resultset = db.query("sql", "select from V where age > ? and city = ?", 18, "Melbourne");
while (resultset.hasNext()) {
  Result record = resultset.next();
  System.out.println( "Found record, name = " + record.getProperty("name"));
}
```

====== query( language, command, callback, parameterMap )

Executes a query taking a map for parameters. This method returns immediately. This method only executes idempotent statements, namely `SELECT` and `MATCH`, that cannot change the database. The execution of any other commands will throw a `IllegalArgumentException` exception.

Syntax:

```java
Resultset query( String language, String command, AsyncResultsetCallback callback, Map<String,Object> parameterMap )
```

Where:

- `language`     is the language to use. Only "SQL" language is supported for now, but in the future multiple languages could be used
- `command`      is the command to execute. If the language supports prepared statements (SQL does), you can specify parameters by name by using `:<arg-name>`
- `callback`     is the callback to execute either if the query succeed (method `onOk()` is called, or in case of error, where the method `onError()` is called
- `parameterMap` this map is used to extract the named parameters

It returns a `Resultset` object where the result can be iterated.

Examples:

```java
Map<String,Object> parameters = new HashMap<>();
parameters.put("age", 18);
parameters.put("city", "Melbourne");

ResultSet resultset = db.query("sql", "select from V where age > :age and city = :city", parameters);
while (resultset.hasNext()) {
  Result record = resultset.next();
  System.out.println( "Found record, name = " + record.getProperty("name"));
}
```

====== command( language, command, callback, positionalParameters )

Executes a command that could change the database. This method returns immediately. This is the equivalent to `query()`, but allows the command to modify the database. Only "SQL" language is supported, but in the future multiple languages could be used.

Syntax:

```java
Resultset command( String language, String command, Object... positionalParameters )
```

Where:

- `language`             is the language to use. Only "SQL" is supported
- `command`              is the command to execute. If the language supports prepared statements (SQL does), you can specify parameters by using `?` for positional replacement or by name by using `:<arg-name>`
- `positionalParameters` optional variable array of parameters to execute with the query


It returns a `Resultset` object where the result can be iterated.

Examples:

Create a new record:


```java
db.async().command("sql", "insert into V set name = 'Jay', surname = 'Miner'", new SQLCallback() {
  @Override
  public void onOk(ResultSet resultset) {
    System.out.println("Created new record: " + resultset.next() );
  }

  @Override
  public void onError(Exception exception) {
    System.err.println("Error on creating new record: " + exception );
  }
});
```

Create a new record by passing position parameters:


```java
db.async().command("sql", "insert into V set name = ? surname = ?", new SQLCallback() {
  @Override
  public void onOk(ResultSet resultset) {
    System.out.println("Created new record: " + resultset.next() );
  }

  @Override
  public void onError(Exception exception) {
    System.err.println("Error on creating new record: " + exception );
  }
}, "Jay", "Miner");
```


====== command( language, command, callback, parameterMap )

Executes a command that could change the database. This method returns immediately. This is the equivalent to `query()`, but allows the command to modify the database. Only "SQL" language is supported, but in the future multiple languages could be used.

Syntax:

```java
Resultset command( String language, String command, Map<String,Object> parameterMap )
```

Where:

- `language`     is the language to use. Only "SQL" is supported
- `command`      is the command to execute. If the language supports prepared statements (SQL does), you can specify parameters by using `?` for positional replacement or by name by using `:<arg-name>`
- `parameterMap` this map is used to extract the named parameters


It returns a `Resultset` object where the result can be iterated.

Examples:

Create a new record by passing a map of parameters:

```java
Map<String,Object> parameters = new HashMap<>();
parameters.put("name", "Jay");
parameters.put("surname", "Miner");

db.async().command("sql", "insert into V set name = :name, surname = :surname", new SQLCallback() {
  @Override
  public void onOk(ResultSet resultset) {
    System.out.println("Created new record: " + resultset.next() );
  }

  @Override
  public void onError(Exception exception) {
    System.err.println("Error on creating new record: " + exception );
  }
}, parameters);
```
