[[MongoDB-API]]
=== MongoDB API

ArcadeDB provides support for both MongoDB Query Language and MongoDB protocol.

==== MongoDB Query Language

If you want to use MongoDB Query Language from <<Java-API>>, you can simply keep the relevant jars in your classpath and execute a query or a command with "mongo" as language.
Example:

```java
// CREATE A NEW DATABASE
Database database = new DatabaseFactory("heroes").create();

// CREATE THE DOCUMENT TYPE 'HEROES'
database.getSchema().createDocumentType("Heros");

// CREATE A NEW DOCUMENT
database.transaction((tx) -> {
  database.newDocument("Heros").set("name", "Jay").set("lastName", "Miner").set("id", i).save();
});

// EXECUTE A QUERY USING MONGO AS QUERY LANGUAGE
for (ResultSet resultset = database.query("mongo", // <-- USE 'mongo' INSTEAD OF 'sql'
    "{ collection: 'Heros', query: { $and: [ { name: { $eq: 'Jay' } }, { lastName: { $exists: true } }, { lastName: { $eq: 'Miner' } }, { lastName: { $ne: 'Miner22' } } ], $orderBy: { id: 1 } } }"); resultset.hasNext(); ++i) {
  Result doc = resultset.next();
  ...
}
```

==== MongoDB Protocol Plugin

If your application is written for https://mongodb.com[MongoDB] and you'd like to run it with ArcadeDB instead, you can simply replace the MongoDB server with ArcadeDB server with the MongoDB Plugin installed.
This plugin supports MongoDB BSON Network protocol.
In this way you can use any MongoDB driver for any supported programming language.

ArcadeDB Server supports a subset of the https://mongodb.com[MongoDB] protocol, like CRUD operations and queries.

To start the MongoDB plugin, enlist it in the <<#_settings,`server.plugins`>> settings.
To specify multiple plugins, use the comma `,` as separator.

Example to start ArcadeDB with the MongoDB Plugin:

```
./server.sh -Darcadedb.server.plugins=MongoDB Protocol:com.arcadedb.mongo.MongoDBProtocolPlugin
```

The Server output will contain this line:

```
2018-10-09 18:47:01:692 INFO  <ArcadeDB_0> - MongoDB Protocol plugin started [ArcadeDBServer]
```
