[[waht_is_arcadedb]]
=== What is ArcadeDB?

ArcadeDB is the new generation of DBMS that runs on pretty much every hardware/software configuration.
ArcadeDB is Multi-Model, that means it can work with graphs, documents and other forms of data.

[discrete]
==== How can it be so fast?

ArcadeDB is written in LLJ ("Low-Level-Java"), that means it's written in Java (Java8+), but without using high-level API. The result is that ArcadeDB does not allocate many objects at run-time on the Heap, so the Garbage Collection doesn't do much.
At the same time, it's still able to run on pretty much every sw/hw configuration and leverage of the hyper optimized Java Virtual Machine*.
Furthermore, the kernel is built to be efficient on multi-core CPUs by using novel Mechanical Sympathy techniques.

[discrete]
==== Cloud DBMS

ArcadeDB was born on the cloud.
Even though you can run ArcadeDB as embedded and in an on-premise setup, you can spin an ArcadeDB server/cluster in a few seconds with Docker, Kubernates, Amazon AWS (coming soon) and Microsoft Azure consoles (coming soon).

[discrete]
==== Is ArcadeDB FREE?

ArcadeDB Community Edition is really FREE for any purpose because released under Apache 2.0 license. We love knowing about your project with ArcadeDB and any contributions back to the Open Community (reports, patches, test cases, documentations, etc) are welcome.
