
=== Console

Run the console by executing `console.sh` under `bin` directory:

```
~/arcadedb $ cd bin
~/arcadedb/bin $ ./console.sh

ArcadeDB Console v.0.1-SNAPSHOT - Copyrights (c) 2020 Arcade Data (https://arcadedata.com)

>
```

The console supports the following commands (you can always retrieve this help by typing `HELP` or just `?`:

```
begin                               -> begins a new transaction
close                               -> closes the database
create database <path>|remote:<url> -> creates a new database
commit                              -> commits current transaction
connect <path>|remote:<url>         -> connects to a database stored on <path>
info types                          -> print available types
info transaction                    -> print current transaction
rollback                            -> rollbacks current transaction
quit or exit                        -> exits from the console
```

==== Tutorial

Let's create our first database "mydb" under the "/temp" directory:

```
> create database /temp/mydb

{mydb}>
```

If you already have a database, you can simply connect to it:

```
> connect /temp/mydb

{mydb}>
```

Now let's create a "Profile" type:

```
{mydb}> create document type Profile

+-----------+--------+
|operation  |typeName|
+-----------+--------+
|create document type|Profile |
+-----------+--------+
Command executed in 176ms
```

Check your new type is there:

```
{mydb}> info types

AVAILABLE TYPES
+-------+--------+------------+-----------+----------+-------------+
|NAME   |TYPE    |PARENT TYPES|BUCKETS    |PROPERTIES|SYNC STRATEGY|
+-------+--------+------------+-----------+----------+-------------+
|Profile|Document|[]          |[Profile_0]|[]        |round-robin  |
+-------+--------+------------+-----------+----------+-------------+
```

Finally, let's create a document of type "Profile":

```
{mydb}> insert into Profile set name = 'Jay', lastName = 'Miner'

+----+-------+----+--------+
|@RID|@TYPE  |name|lastName|
+----+-------+----+--------+
|#1:0|Profile|Jay |Miner   |
+----+-------+----+--------+
Command executed in 29ms
```

You can see your brand new record with RID #1:0. Now let's query the database to see if our new document can be found:

```
{mydb}> select from Profile

+----+-------+----+--------+
|@RID|@TYPE  |name|lastName|
+----+-------+----+--------+
|#1:0|Profile|Jay |Miner   |
+----+-------+----+--------+
Command executed in 33ms
```

Here we go: our document is there.

Remember that a transaction is automatically started. In order to make changes persistent, execute a `commit` command. When the
console exists (`exit` or `quit` command), the pending transaction is committed automatically.

