[[sql-buckets]]
==== Buckets

[[sql-create-bucket]]
===== SQL - `CREATE BUCKET`


Creates a new bucket in the database. Once created, you can use the bucket to save records by specifying its name during saves. If you want to add the new bucket to a type, follow its creation with the <<sql-alter-type,`ALTER TYPE`>> command.

*Syntax*

[source,sql]
----
CREATE BUCKET <bucket> [ID <bucket-id>]

----

* *`&lt;bucket&gt;`* Defines the name of the bucket you want to create. You must use a letter for the first character, for all other characters, you can use alphanumeric characters, underscores and dashes.
* *`&lt;bucket-id&gt;`* Defines the numeric ID you want to use for the bucket.

*Examples*

* Create the bucket `account`:

----
ArcadeDB> CREATE BUCKET account
----

____

For more information see:

____

* <<sql-drop-bucket,`DROP BUCKET`>>

[[sql-drop-bucket]]
===== SQL - `DROP BUCKET`


Removes the bucket and all of its content. This operation is permanent and cannot be rolled back.

*Syntax*

[source,sql]
----
DROP BUCKET <bucket-name>|<bucket-id>

----

* *`&lt;bucket-name&gt;`* Defines the name of the bucket you want to remove.
* *`&lt;bucket-id&gt;`* Defines the ID of the bucket you want to remove.

*Examples*

* Remove the bucket `Account`:

----
ArcadeDB> DROP BUCKET Account
----

For more information, see:

* <<sql-create-bucket,`CREATE BUCKET`>>
* <<sql-drop-type,`DROP TYPE`>>

[[sql-truncate-bucket]]
===== SQL - `TRUNCATE BUCKET`


Deletes all records of a bucket. This command operates at a lower level than the standard <<sql-delete,`DELETE`>> command.

Truncation is not permitted on vertex or edge types, but you can force its execution using the `UNSAFE` keyword. Forcing truncation is strongly discouraged, as it can leave the graph in an inconsistent state.

*Syntax*

----
TRUNCATE BUCKET <bucket>

----

* *`&lt;bucket&gt;`* Defines the bucket to delete.
* *`UNSAFE`* Defines whether the command forces the truncation on vertex or edge types.

*Examples*

* Remove all records in the bucket `profile`:

----
ArcadeDB> TRUNCATE BUCKET profile
----

For more information, see:

* <<sql-delete,`DELETE`>>
* <<sql-truncate-type,`TRUNCATE TYPE`>>
