[[binaries]]
==== Installations from Binaries

ArcadeDB is released for both Java 17 and Java 21.

Java 21 packages are available through https://github.com/ArcadeData/arcadedb/releases[GitHub releases page] or https://repo1.maven.org/maven2/com/arcadedb/arcadedb-package/[Maven central].

Java 17 packages are available through https://github.com/orgs/ArcadeData/packages[Github packages page].

Download the package suitable for your platform and follow the instructions below.

1. Unpack `tar -xzf arcadedb-{revnumber}.tar.gz`
* Change into directory: `cd arcadedb-{revnumber}`

2. Launch server
* Linux / MacOS: `bin/server.sh`
* Windows: `bin\server.bat`

3. Exit server via **CTRL+C**

4. Interact with server
* Studio: http://localhost:2480[`http://localhost:2480`]
* Console:
** Linux / MacOS: `bin/console.sh`
** Windows: `bin\console.bat`

5. Exit server via **CTRL+C**

[discrete]
===== Binaries

[%header,cols=3]
|===
|                     | **Linux** / **Mac** | **Windows**
| <<server,Server>>  | `bin/server.sh`     | `bin\server.bat`
| <<console,Console>> | `bin/console.sh`    | `bin\console.bat`
|===


==== Mac OS X

Popular way to get opensource software is to use https://brew.sh[homebrew project].

Currently, ArcadeDB is not available through an official Homebrew formula.
To install ArcadeDB on Mac OS X:

1. Download the latest release from https://github.com/ArcadeData/arcadedb/releases
2. Extract the archive to your preferred location (e.g., `/usr/local/arcadedb`)
3. Add the `bin` directory to your PATH:

[source,bash]
----
echo 'export PATH="/usr/local/arcadedb/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc
----

==== Windows via Scoop

Instead of using manual install you can use Scoop installer, instructions are available on their https://scoop.sh[project website].

[#scoop-installer,powershell]
----
scoop bucket add extras
scoop install arcadedb
----

This downloads and installs ArcadeDB on your box and makes following two commands available:

[#scoop-shims,powershell]
----
arcadedb-console
arcadedb-server
----

You should use these instead of `bin\console.bat` and `bin\server.bat` mentioned above.


