#!/usr/bin/env python3
"""
Emit a legacy-anchor -> new-Antora-URL mapping for the docs cutover.

The legacy build at docs.arcadedb.com is a single page; every anchor
lives at docs.arcadedb.com/#<anchor>. After the cutover, anchors live
on individual Antora pages at docs.arcadedb.com/arcadedb/<path>.html
(plus an optional #<anchor> if the target page contains more than
one anchor).

This script walks docs/modules/ROOT/pages/, builds the same anchor map
that rewrite-xrefs.py uses, and writes:

  URL-MIGRATION.md             — human-readable Markdown table for the
                                  website agent to update links.
  scripts/url-migration-map.tsv — tab-separated file (legacy URL,
                                  new URL, anchor id, page path) for
                                  programmatic consumption.

Run from the repo root:
  python3 scripts/url-migration-map.py
"""
from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PAGES = REPO / "docs" / "modules" / "ROOT" / "pages"

# Same regexes as rewrite-xrefs.py so the two stay in sync.
ANCHOR_RE = re.compile(r"^\[\[([a-zA-Z_][a-zA-Z0-9_.\-]*)\]\]\s*$", re.MULTILINE)
BLOCK_ID_RE = re.compile(
    r"^\[#([a-zA-Z_][a-zA-Z0-9_.\-]*)(?:,[^\]]+)?\]\s*$", re.MULTILINE
)

LEGACY_BASE = "https://docs.arcadedb.com/"
NEW_BASE = "https://docs.arcadedb.com/arcadedb/"


def find_anchors(text: str) -> list[str]:
    """Return anchors in source order, preserving duplicates so the
    earliest occurrence on a page wins for the per-page anchor."""
    out: list[str] = []
    for m in re.finditer(ANCHOR_RE, text):
        out.append(m.group(1))
    for m in re.finditer(BLOCK_ID_RE, text):
        out.append(m.group(1))
    return out


def main() -> int:
    pages = sorted(PAGES.rglob("*.adoc"))
    # anchor -> (page_rel, is_first_anchor_on_page)
    anchor_to_page: dict[str, str] = {}
    page_first_anchor: dict[str, str] = {}
    duplicates: dict[str, list[str]] = defaultdict(list)

    for p in pages:
        rel = p.relative_to(PAGES).as_posix()
        text = p.read_text(encoding="utf-8")
        anchors = find_anchors(text)
        if anchors:
            page_first_anchor[rel] = anchors[0]
        for a in anchors:
            if a in anchor_to_page:
                duplicates[a].append(rel)
            else:
                anchor_to_page[a] = rel

    rows: list[tuple[str, str, str, str, bool]] = []  # legacy, new, anchor, page, dup
    for anchor in sorted(anchor_to_page):
        rel = anchor_to_page[anchor]
        page_url = NEW_BASE + rel.replace(".adoc", ".html")
        # If this anchor is the first/primary one on its page, the new
        # canonical URL doesn't need the #anchor — it's the page itself.
        is_primary = page_first_anchor.get(rel) == anchor
        new_url = page_url if is_primary else f"{page_url}#{anchor}"
        legacy_url = f"{LEGACY_BASE}#{anchor}"
        rows.append((legacy_url, new_url, anchor, rel, anchor in duplicates))

    md_out = REPO / "URL-MIGRATION.md"
    tsv_out = REPO / "scripts" / "url-migration-map.tsv"

    with md_out.open("w", encoding="utf-8") as f:
        f.write("# Legacy -> Antora URL migration map\n\n")
        f.write(
            f"Generated by `scripts/url-migration-map.py` from "
            f"`docs/modules/ROOT/pages/`. "
            f"{len(rows)} legacy fragment URLs map to {len(set(r[3] for r in rows))} "
            f"new Antora pages.\n\n"
        )
        f.write(
            "When a row's *new URL* has no `#anchor`, the anchor is the "
            "first one on its target page and the page URL alone is the "
            "canonical destination.\n\n"
        )
        if duplicates:
            f.write(
                f"⚠️  {len(duplicates)} anchors are defined on more than one "
                "page; the first occurrence wins. Review the *Duplicate anchors* "
                "section at the bottom and pick the right canonical URL by "
                "context if the legacy link's intent is ambiguous.\n\n"
            )
        f.write("| Legacy URL | New URL |\n")
        f.write("| --- | --- |\n")
        for legacy, new, _, _, _ in rows:
            f.write(f"| `{legacy}` | `{new}` |\n")
        if duplicates:
            f.write("\n## Duplicate anchors (review by context)\n\n")
            f.write("| Anchor | Pages defining it |\n")
            f.write("| --- | --- |\n")
            for anchor in sorted(duplicates):
                primary = anchor_to_page[anchor]
                others = duplicates[anchor]
                pages_str = ", ".join([primary] + others)
                f.write(f"| `{anchor}` | {pages_str} |\n")

    with tsv_out.open("w", encoding="utf-8") as f:
        f.write("legacy_url\tnew_url\tanchor\tpage\tduplicate\n")
        for legacy, new, anchor, page, dup in rows:
            f.write(f"{legacy}\t{new}\t{anchor}\t{page}\t{int(dup)}\n")

    print(f"Wrote {md_out.relative_to(REPO)} ({len(rows)} rows)")
    print(f"Wrote {tsv_out.relative_to(REPO)}")
    if duplicates:
        print(f"Note: {len(duplicates)} anchors duplicated across pages — see the report")
    return 0


if __name__ == "__main__":
    sys.exit(main())
