[[schema]]
= Schema

ArcadeDB supports schema-less, schema-full and hybrid operation.
This means for all types that have a declared schema it is applied.
Minimally, a type (document, vertex or edge) needs to be declared in a database to be able to insert to,
i.e. xref:reference/sql/sql-create-type.adoc#sql-create-type[CREATE TYPE (SQL)] and xref:reference/sql/sql-alter-type.adoc#sql-alter-type[ALTER TYPE (SQL)].
Beyond the type, declaration properties with or without constraints, can be declared,
i.e. xref:reference/sql/sql-create-property.adoc#sql-create-property[CREATE PROPERTY (SQL)] and xref:reference/sql/sql-alter-property.adoc#sql-alter-property[ALTER PROPERTY (SQL)].
Inserting into a declared type, all datasets are accepted (even with additional undeclared properties) as long as no property constraints are violated.

For heavy property values such as vector embeddings, large strings or embedded JSON, properties can be flagged as xref:concepts/external-properties.adoc#external-properties[`EXTERNAL`] so that the value is stored in a paired bucket and the primary record stays small.
