[[graph-database]]
=== Graph Database

ArcadeDB is a native graph database;
and in this section we explain what this means and how this relates to applications.

[discrete]
==== Graph Components 

Essentially a graph is tuple, or pair of sets, of vertices (aka nodes) and edges (aka arcs),
whereas the set of vertices contains an (indexed) set of objects,
and the set of edges contains (at least) pairs specifying a respective edge's endpoints.

A particular type of graph is the https://en.wikipedia.org/wiki/Directed_graph[directed graph],
which is characterized by oriented edges, meaning each edge's pair is ordered.
A simple example of a directed graph is given by:

.Directed Graph
[d2,directed-graph]
....
vars: {
  d2-config: {
    sketch: true
  }
}
direction: right
v_1: {
  shape: circle
  label: "v_1"
}
v_2: {
  shape: circle
  label: "v_2"
}
v_1 <-> v_2: e_(1,2)
....

with:

- Vertices: V = {v_1, v_2}
- Edges: E = {e_(1,2)}

[discrete]
==== Graph Database Types

There are two common types of graph databases,
which are instances of directed graphs,
but differ by the underlying objects of vertices and edges:

1. **Knowledge Graph**: the underlying vertex and edge objects are (just) labels.
2. **Property Graph**: the underlying vertex and edge objects are (labeled) documents.

ArcadeDB is a property graph, which means a vertex or edge consists of an identifier (RID),
a label (type), and properties (document), in addition to the ordered pairs of endpoints.
The latter are here vertex properties of incoming and outgoing edges, instead of edge properties of ordered vertex pairs, for technical reasons.

[discrete]
==== Why (Property) Graph Databases?

- The modeled domain is already a network.
- Fast traversal of relations instead of costly joins in relational databases.
- Naturally annotated edges instead of inconvenient reification in knowledge graphs.
