[[remote-tutorial]]
=== 10-Minute Tutorial (Remote)

The ArcadeDB Server is accessible from the remote through the HTTP/JSON protocol.
The protocol is very simple.
For this reason, you don't need a driver, because every modern programming language provides an easy way to execute HTTP requests and parse JSON.

For the examples in this tutorial we're going to use https://curl.se/[`curl`].
Every request must be authenticated by passing user and password as HTTP basic authentication (in HTTP Headers).
In the examples below we're going to always use "root" user with password "arcadedb-password".

NOTE: Under Windows (Powershell) single and double quotes inside a single or double quoted string need to be replaced with their Unicode entity representations `\u0022` (double quote) and
`\u0027` (single quote).
This is for example the case in the data argument (`-d`) of POST requests.

Let's first create an empty database "school" on the server:

[source,shell]
----
$ curl -X POST http://localhost:2480/api/v1/server \
       -d '{ "command": "create database school" }' \
       -H "Content-Type: application/json" \
       --user root:arcadedb-password
----

Now let's create the type "Class":

[source,shell]
----
$ curl -X POST http://localhost:2480/api/v1/command/school \
       -d '{ "language": "sql", "command": "create document type Class"}' \
       -H "Content-Type: application/json" \
       --user root:arcadedb-password
----

We could insert our first Class by using SQL:

[source,shell]
----
$ curl -X POST http://localhost:2480/api/v1/command/school \
       -d '{ "language": "sql", "command": "insert into Class set name = '\''English'\'', location =  '\''3rd floor'\''"}' \
       -H "Content-Type: application/json" \
       --user root:arcadedb-password
----

Or better, using parameters with SQL:

[source,shell]
----
$ curl -X POST http://localhost:2480/api/v1/command/school \
       -d '{ "language": "sql", "command": "insert into Class set name = :name, location = :location", "params": { "name": "English", "location": "3rd floor" }}' \
       -H "Content-Type: application/json" \
       --user root:arcadedb-password
----

For more detailed information about the HTTP/JSON protocol, see the <<http-json-protocol,HTTP/JSON Protocol>> section.