name: Generate Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@b1de5da23ed0a6d14e0aeee8ed52fdd87af2363c # v2.0.2

      - uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set prod env var
        id: set-prod
        run: echo "prod=$([[ $GITHUB_REF == refs/heads/main ]] && echo true || echo false)" >> $GITHUB_ENV

      - name: Generate Site
        run: mvn generate-resources

      - uses: jsmrcaga/action-netlify-deploy@ae36ac1b3d1ad3646eecb5631977e7314d3a6a2f # v2.4.0
        with:
          build_directory: ./target/generated-docs/
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: ${{ env.prod }}

      - name: Preview URL
        run: echo "${{ env.NETLIFY_PREVIEW_URL }}"
