[[Secrets]]
=== Handling Secrets

Passing secrets, like passwords, safely to the server, especially in containers, can be tricky.
For example, the settings:
```
-Darcadedb.server.rootPassword=password
```
for the root password, or:
```
-Darcadedb.server.defaultDatabases=database[username:password]
```
for database and user generation are comfortable,
but present the issue that passwords passed this way are readable in plaint text
in applications like `htop` or `docker compose top`.
This is the case because these settings are passed ultimately via command-line to the JVM (even if using `JAVA_OPTS` or `ARCADEDB_SETTINGS`).

In the following, an approach is presented to avoid this problem.
The idea is to use the special environment variable https://docs.oracle.com/en/java/javase/11/troubleshoot/environment-variables-and-system-properties.html#GUID-BE6E7B7F-A4BE-45C0-9078-AA8A66754B97[`JAVA_TOOL_OPTIONS`] to pass the settings
directly into the JVM (alternatively https://docs.oracle.com/en/java/javase/11/tools/java.html#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE__USINGTHEJDK_JAVA_OPTIONSLAUNCHERENV-F3C0E3BA[`JDK_JAVA_OPTIONS`] or the undocumented `_JAVA_OPTIONS` may be used).
However, just using this particular environment variable would mean that the
JVM writes the contents of this variable to the standard error stream,
which means the secrets would appear in logs.
To suppress this logging, a https://superuser.com/a/585696/1824014[workaround] can be used
by wrapping the `server.sh` script:

```shell
#!/bin/sh

export JAVA_TOOL_OPTIONS="-Darcadedb.server.rootPassword=`cat /path/to/root_secret` -Darcadedb.server.defaultDatabases=database1[user1:`cat /path/to/user_secret`]"
./bin/server.sh 2> >(grep -v "^Picked up JAVA_TOOL_OPTIONS:") &

PID="$!"

unset JAVA_TOOL_OPTIONS

wait $PID
```

This way the secrets are passed directly into the JVM without being resolved before,
and the `stderr` logging is filtered.
The server is send to the background and its process ID saved.
Then, by unsetting the `JAVA_TOOL_OPTIONS` variable immediately after using it,
ensures the secrets will not linger in the environment.
